server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/auctions
    username: postgres
    password: eecs4413
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show_sql: false
  main:
    web-application-type: servlet

controllerServer:
  port: 8080

itemServer:
  port: 8082