server:
  port: 8080
  apiKey: "O8bsJhrjp8LIkSXMl7f5ymD8id0eJzJQ1LFFS5dfHds1rdjkm9Zn3uGEeCQs6B4YB2KUjfbcWL8ImQfxyQOBZDtrFhYOX4EtG20bNiBHzh130AuxOYjnMwEHkDBrTZaP"

auctionServer:
  url: "http://localhost"
  port: 8083
  apiKey: "V6ZQnmzX5o7tDv5h6PGp9dvaxEbaRxIv3SZHaaCrbXT90hg7ftGrTKjRv1RncS1kr9s9QHeqP6Iupy4dMtnjdRSkZa4cw6ZwDIwN7ZYe2Yyr6KIRaRMXDWT8BSsD9BoH"

itemServer:
  url: "http://localhost"
  port: 8082
  apiKey: "8obdVwEBLtNaht6mJrjC54wik1jAHdFLeCoP8yGlho7N9pdQpld2C5KfSt7pvMMyDPHHvTSJBJXEVQ8GD5n2nCvdyP0k39PdzgwB3QcD91j3J3Bf242nEIlzW9SNUtOu"

paymentServer:
  url: "http://localhost"
  port: 8084
  apiKey: "Nn0NFACZliR6aDRROAZAVolhFg4XaP5P27cD4IIkENtRIrVtdUW4HpHFW8pJn0cM88pPdVDaF45xNgTBbheHMiKexFHibwgQTLYLp5MjVQMCqk76PCPmo8d44EKF4VT1"

userServer:
  url: http://localhost
  port: 8081
  apiKey: "iwSo3cLAwWlXzfCBsyRs9tQVU9LMPyy1ZNWceHWd1UoaNVqA65nPC0bK6nrQByC7BWDMOQrJb3ShQQxD4rTaypyJlkAJeTFFJwoTlepq4AcJtaZgBabPORrqRAIFdM9y"
