server:
  port : 8080

auctionServer:
  port: 8083

itemServer:
  port: 8082

paymentServer:
  port: 8084

userServer:
  port: 8081
  apiKey: "iwSo3cLAwWlXzfCBsyRs9tQVU9LMPyy1ZNWceHWd1UoaNVqA65nPC0bK6nrQByC7BWDMOQrJb3ShQQxD4rTaypyJlkAJeTFFJwoTlepq4AcJtaZgBabPORrqRAIFdM9y"
